<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        \DB::statement('PRAGMA foreign_keys = OFF');
        Product::truncate();
        \DB::statement('PRAGMA foreign_keys = ON');

        $products = [
            // ==================== STORE 1 — Toko Elektronik Makmur ====================
            ['store_id' => 1, 'name' => 'Laptop Gaming XYZ Pro',       'category' => 'Electronics', 'brand' => 'XYZ Brand',   'price' => 14500000, 'original_price' => 17000000, 'stock' => 8,   'weight' => 2200, 'description' => 'Laptop gaming berperforma tinggi dengan GPU RTX 4060 dan prosesor Intel Core i7 generasi terbaru. Mampu menjalankan game AAA di setting ultra tanpa hambatan. Dilengkapi layar 144Hz dengan panel IPS untuk pengalaman visual yang halus dan akurat, serta sistem pendingin dual-fan untuk menjaga performa tetap optimal.', 'specifications' => ['RAM' => '32GB', 'Storage' => '1TB SSD', 'GPU' => 'RTX 4060', 'Color' => 'Black']],
            ['store_id' => 1, 'name' => 'Laptop Ultrabook Slim',        'category' => 'Electronics', 'brand' => 'SlimBook',     'price' => 9800000,  'stock' => 12,  'weight' => 1400, 'description' => 'Laptop tipis berbobot hanya 1.4kg, ideal untuk profesional yang selalu mobile. Desain premium dengan bodi aluminium yang kokoh namun ringan. Baterai tahan hingga 12 jam pemakaian aktif sehingga kamu bisa bekerja seharian tanpa khawatir kehabisan daya.', 'specifications' => ['RAM' => '16GB', 'Storage' => '512GB SSD', 'Battery' => '12h', 'Color' => 'Silver']],
            ['store_id' => 1, 'name' => 'Laptop Business Series',       'category' => 'Electronics', 'brand' => 'BizPro',       'price' => 11200000, 'original_price' => 14000000, 'stock' => 6,   'weight' => 1800, 'description' => 'Laptop Business Series dirancang khusus untuk kebutuhan profesional dengan performa tinggi dan desain tipis yang elegan. Ditenagai prosesor terbaru dengan RAM 16GB, laptop ini mampu menjalankan berbagai aplikasi bisnis secara multitasking tanpa hambatan. Dilengkapi dengan layar anti-silau yang nyaman untuk penggunaan lama, serta baterai tahan lama hingga 10 jam pemakaian aktif.', 'specifications' => ['RAM' => '16GB', 'Storage' => '512GB', 'OS' => 'Windows 11 Pro', 'Color' => 'Gray']],
            ['store_id' => 1, 'name' => 'Smartphone Pro Max',           'category' => 'Electronics', 'brand' => 'ProMax',       'price' => 5500000,  'original_price' => 6500000,  'stock' => 25,  'weight' => 200,  'description' => 'Smartphone flagship dengan kamera utama 108MP yang menghasilkan foto tajam bahkan di kondisi minim cahaya. Layar AMOLED 6.7 inci 120Hz memberikan tampilan yang memukau. Chipset terbaru dan RAM 8GB memastikan performa kencang untuk gaming dan multitasking.', 'specifications' => ['RAM' => '8GB', 'Storage' => '256GB', 'Color' => 'Silver']],
            ['store_id' => 1, 'name' => 'Smartphone Ultra 5G',          'category' => 'Electronics', 'brand' => 'UltraPhone',   'price' => 7200000,  'stock' => 15,  'weight' => 210,  'description' => 'Smartphone 5G dengan konektivitas ultra-cepat untuk streaming dan download tanpa lag. Layar Dynamic AMOLED 6.8 inci dengan refresh rate 120Hz memberikan pengalaman visual premium. Baterai 5000mAh dengan pengisian cepat 65W memastikan perangkat siap digunakan sepanjang hari.', 'specifications' => ['RAM' => '12GB', 'Storage' => '512GB', '5G' => 'Yes', 'Color' => 'Midnight Blue']],
            ['store_id' => 1, 'name' => 'Smartphone Entry Level',       'category' => 'Electronics', 'brand' => 'BudgetPhone',  'price' => 1800000,  'stock' => 50,  'weight' => 180,  'description' => 'Smartphone terjangkau dengan fitur lengkap untuk kebutuhan sehari-hari. Layar 6.5 inci HD+ IPS nyaman untuk menonton video dan berselancar di media sosial. Kamera triple 48MP menghasilkan foto berkualitas baik di berbagai kondisi pencahayaan.', 'specifications' => ['RAM' => '4GB', 'Storage' => '64GB', 'Color' => 'White']],
            ['store_id' => 1, 'name' => 'Headphone Wireless ANC',       'category' => 'Electronics', 'brand' => 'SoundPro',     'price' => 850000,   'original_price' => 1050000,  'stock' => 30,  'weight' => 300,  'description' => 'Headphone over-ear dengan teknologi Active Noise Cancellation (ANC) yang efektif meredam kebisingan sekitar. Koneksi Bluetooth 5.0 stabil dengan jangkauan hingga 10 meter. Baterai tahan 30 jam pemakaian, cocok untuk perjalanan jauh atau seharian bekerja dari rumah.', 'specifications' => ['Battery' => '30h', 'ANC' => 'Yes', 'Connectivity' => 'Bluetooth 5.0']],
            ['store_id' => 1, 'name' => 'Earbuds TWS Pro',              'category' => 'Electronics', 'brand' => 'SoundPro',     'price' => 450000,   'stock' => 40,  'weight' => 60,   'description' => 'True Wireless Stereo earbuds dengan suara jernih dan bass yang dalam. Rating IPX5 membuatnya tahan cipratan air dan keringat sehingga aman digunakan saat olahraga. Charging case memberikan daya tambahan hingga total 32 jam pemakaian.', 'specifications' => ['Battery' => '8h', 'Water Resistant' => 'IPX5', 'Connectivity' => 'Bluetooth 5.2']],
            ['store_id' => 1, 'name' => 'Speaker Bluetooth Portable',   'category' => 'Electronics', 'brand' => 'BoomBox',      'price' => 380000,   'stock' => 35,  'weight' => 500,  'description' => 'Speaker portable dengan suara keras dan jernih bertenaga 20W. Desain kompak mudah dibawa ke mana saja. Rating IPX7 membuatnya tahan direndam air hingga 1 meter, cocok untuk digunakan di pantai, kolam renang, atau saat hiking.', 'specifications' => ['Battery' => '12h', 'Water Resistant' => 'IPX7', 'Power' => '20W']],
            ['store_id' => 1, 'name' => 'Tablet 10 Inch',               'category' => 'Electronics', 'brand' => 'TabPro',       'price' => 3200000,  'original_price' => 3800000,  'stock' => 20,  'weight' => 480,  'description' => 'Tablet berperforma tinggi dengan layar 10.4 inci LCD 2K yang luas dan tajam. RAM 6GB dan prosesor octa-core memastikan pengalaman multitasking yang mulus. Cocok untuk belajar, hiburan, hingga pekerjaan ringan seperti mengedit dokumen dan presentasi.', 'specifications' => ['RAM' => '6GB', 'Storage' => '128GB', 'Display' => '10.4 inch', 'Color' => 'Space Gray']],
            ['store_id' => 1, 'name' => 'Smartwatch Series 5',          'category' => 'Electronics', 'brand' => 'WatchPro',     'price' => 1250000,  'stock' => 22,  'weight' => 45,   'description' => 'Smartwatch multifungsi yang memantau kesehatan 24 jam: detak jantung, kadar oksigen darah (SpO2), dan kualitas tidur. GPS terintegrasi untuk tracking aktivitas outdoor tanpa perlu membawa ponsel. Rating IP68 tahan debu dan air.', 'specifications' => ['Battery' => '7 days', 'Water Resistant' => 'IP68', 'GPS' => 'Yes']],
            ['store_id' => 1, 'name' => 'Kamera DSLR Beginner',         'category' => 'Electronics', 'brand' => 'SnapShot',     'price' => 6500000,  'stock' => 7,   'weight' => 600,  'description' => 'Kamera DSLR entry-level yang sempurna untuk pemula yang ingin belajar fotografi. Sensor 24MP menghasilkan foto detail dengan dynamic range yang luas. Paket sudah termasuk lensa kit 18-55mm yang serbaguna untuk berbagai kondisi pemotretan. Mendukung perekaman video 4K.', 'specifications' => ['Megapixel' => '24MP', 'Lens' => '18-55mm', 'Video' => '4K']],
            ['store_id' => 1, 'name' => 'Kamera Action Cam 4K',         'category' => 'Electronics', 'brand' => 'ActionCam',    'price' => 1800000,  'stock' => 18,  'weight' => 120,  'description' => 'Action cam ringkas untuk merekam momen petualanganmu dalam resolusi 4K 60fps yang sinematik. Tahan air hingga kedalaman 10 meter tanpa casing tambahan. Dilengkapi stabilisasi gambar elektronik (EIS) untuk video yang mulus meski saat bergerak cepat.', 'specifications' => ['Resolution' => '4K 60fps', 'Water Resistant' => '10m', 'Battery' => '2h']],
            ['store_id' => 1, 'name' => 'Monitor Gaming 144Hz',         'category' => 'Electronics', 'brand' => 'ViewPro',      'price' => 2800000,  'original_price' => 3200000,  'stock' => 10,  'weight' => 3500, 'description' => 'Monitor gaming 27 inci dengan panel IPS resolusi 2K (2560x1440) yang menghadirkan warna akurat dan sudut pandang luas. Refresh rate 144Hz dengan response time 1ms memberikan keunggulan kompetitif dalam game FPS dan action.', 'specifications' => ['Size' => '27 inch', 'Refresh Rate' => '144Hz', 'Panel' => 'IPS', 'Resolution' => '2K']],
            ['store_id' => 1, 'name' => 'Monitor Ultrawide Curved',     'category' => 'Electronics', 'brand' => 'ViewPro',      'price' => 4200000,  'stock' => 5,   'weight' => 5000, 'description' => 'Monitor ultrawide 34 inci dengan kelengkungan 1500R yang memanjakan mata dan meningkatkan produktivitas. Resolusi UWQHD (3440x1440) memberikan ruang kerja yang luas untuk multitasking. Cocok untuk desainer grafis, video editor, dan gamer yang menginginkan pengalaman imersif.', 'specifications' => ['Size' => '34 inch', 'Refresh Rate' => '100Hz', 'Resolution' => 'UWQHD']],
            ['store_id' => 1, 'name' => 'Keyboard Mechanical RGB',      'category' => 'Electronics', 'brand' => 'TypeMaster',   'price' => 650000,   'stock' => 28,  'weight' => 900,  'description' => 'Keyboard mechanical tenkeyless dengan switch Red yang ringan dan responsif, ideal untuk gaming dan mengetik cepat. Backlighting RGB per-key yang bisa dikustomisasi sesuai selera. Build quality solid dengan bodi aluminium yang kokoh.', 'specifications' => ['Switch' => 'Red', 'Layout' => 'TKL', 'RGB' => 'Per-key']],
            ['store_id' => 1, 'name' => 'Mouse Gaming Wireless',        'category' => 'Electronics', 'brand' => 'ClickPro',     'price' => 480000,   'stock' => 32,  'weight' => 95,   'description' => 'Mouse gaming wireless dengan sensor optik presisi tinggi hingga 25.000 DPI untuk akurasi yang sempurna. Koneksi 2.4GHz ultra-low latency memastikan respons yang sama cepatnya dengan mouse kabel. Baterai tahan hingga 70 jam pemakaian.', 'specifications' => ['DPI' => '25000', 'Battery' => '70h', 'Polling Rate' => '1000Hz']],
            ['store_id' => 1, 'name' => 'Router WiFi 6 Dual Band',      'category' => 'Electronics', 'brand' => 'NetPro',       'price' => 950000,   'stock' => 15,  'weight' => 400,  'description' => 'Router WiFi 6 (802.11ax) dengan kecepatan hingga 3000 Mbps untuk rumah atau kantor kecil. Teknologi OFDMA dan MU-MIMO memungkinkan banyak perangkat terhubung secara bersamaan tanpa penurunan kecepatan. Empat antena eksternal menjangkau seluruh area rumah.', 'specifications' => ['Speed' => 'AX3000', 'Band' => 'Dual', 'Antenna' => '4']],
            ['store_id' => 1, 'name' => 'Power Bank 20000mAh',          'category' => 'Electronics', 'brand' => 'ChargePro',    'price' => 320000,   'stock' => 45,  'weight' => 380,  'description' => 'Power bank kapasitas besar 20.000mAh yang cukup untuk mengisi daya smartphone 4-5 kali. Dukungan pengisian cepat 65W PD memungkinkan pengisian laptop. Dilengkapi dua port output USB-C dan USB-A untuk mengisi dua perangkat sekaligus.', 'specifications' => ['Capacity' => '20000mAh', 'Input' => 'USB-C', 'Output' => '65W PD']],
            ['store_id' => 1, 'name' => 'Charger GaN 65W',              'category' => 'Electronics', 'brand' => 'ChargePro',    'price' => 185000,   'stock' => 60,  'weight' => 100,  'description' => 'Charger GaN (Gallium Nitride) generasi terbaru yang 40% lebih kecil dari charger konvensional namun menghasilkan daya hingga 65W. Mendukung pengisian cepat PD 3.0 untuk laptop, tablet, dan smartphone. Tiga port memungkinkan pengisian tiga perangkat sekaligus.', 'specifications' => ['Wattage' => '65W', 'Ports' => '2 USB-C + 1 USB-A', 'Technology' => 'GaN']],
            ['store_id' => 1, 'name' => 'SSD Eksternal 1TB',            'category' => 'Electronics', 'brand' => 'StoragePro',   'price' => 750000,   'stock' => 20,  'weight' => 50,   'description' => 'SSD eksternal ultraportable berkapasitas 1TB dengan kecepatan baca hingga 1050 MB/s melalui interface USB 3.2 Gen 2. Bodinya yang kecil dan ringan mudah masuk saku. Cocok untuk menyimpan dan mentransfer file besar seperti video 4K dengan cepat.', 'specifications' => ['Capacity' => '1TB', 'Speed' => '1050 MB/s', 'Interface' => 'USB 3.2']],
            ['store_id' => 1, 'name' => 'Flash Disk 64GB USB 3.0',      'category' => 'Electronics', 'brand' => 'StoragePro',   'price' => 85000,    'stock' => 100, 'weight' => 10,   'description' => 'Flash disk compact berkapasitas 64GB dengan kecepatan transfer USB 3.0 hingga 100 MB/s. Desain mini yang tidak menonjol sehingga bisa tetap terpasang di laptop. Cocok untuk menyimpan file penting, presentasi, atau data backup.', 'specifications' => ['Capacity' => '64GB', 'Speed' => '100 MB/s', 'Interface' => 'USB 3.0']],
            ['store_id' => 1, 'name' => 'Webcam HD 1080p',              'category' => 'Electronics', 'brand' => 'CamPro',       'price' => 280000,   'stock' => 25,  'weight' => 150,  'description' => 'Webcam plug-and-play beresolusi 1080p dengan frame rate 60fps untuk video call yang jernih dan mulus. Autofocus otomatis memastikan wajahmu selalu tampak tajam. Mikrofon built-in dengan noise reduction menghasilkan suara bersih tanpa gangguan kebisingan sekitar.', 'specifications' => ['Resolution' => '1080p 60fps', 'Autofocus' => 'Yes', 'Mic' => 'Built-in']],
            ['store_id' => 1, 'name' => 'Mikrofon Kondenser USB',       'category' => 'Electronics', 'brand' => 'VoicePro',     'price' => 420000,   'stock' => 18,  'weight' => 350,  'description' => 'Mikrofon kondenser USB dengan pola tangkap cardioid yang ideal untuk podcast, voiceover, streaming, dan rekaman vokal. Plug-and-play tanpa perlu driver atau audio interface tambahan. Dilengkapi pop filter dan shock mount untuk suara yang bersih dan profesional.', 'specifications' => ['Pattern' => 'Cardioid', 'Frequency' => '20Hz-20kHz', 'Interface' => 'USB']],
            ['store_id' => 1, 'name' => 'Drone Mini 4K',                'category' => 'Electronics', 'brand' => 'SkyPro',       'price' => 2200000,  'original_price' => 2700000,  'stock' => 8,   'weight' => 250,  'description' => 'Drone mini berbobot kurang dari 250g sehingga bebas regulasi di banyak negara. Kamera 4K stabilized menghasilkan foto dan video aerial yang sinematik. Waktu terbang hingga 31 menit dengan jangkauan kendali 10km. Dilengkapi mode follow-me dan obstacle avoidance.', 'specifications' => ['Camera' => '4K', 'Flight Time' => '31min', 'Range' => '10km']],
            ['store_id' => 1, 'name' => 'Konsol Game Portable',         'category' => 'Electronics', 'brand' => 'GamePro',      'price' => 3500000,  'stock' => 10,  'weight' => 400,  'description' => 'Konsol game portable dengan layar OLED 7 inci yang jernih dan warna yang kaya. Bisa dimainkan sebagai handheld maupun dihubungkan ke TV. Tersedia ribuan judul game dari berbagai genre. Baterai tahan hingga 12 jam untuk sesi gaming maraton.', 'specifications' => ['Storage' => '64GB', 'Display' => '7 inch OLED', 'Battery' => '12h']],
            ['store_id' => 1, 'name' => 'Smart TV 43 Inch 4K',          'category' => 'Electronics', 'brand' => 'ViewMax',      'price' => 4800000,  'original_price' => 5500000,  'stock' => 6,   'weight' => 8000, 'description' => 'Smart TV 43 inci dengan panel VA resolusi 4K UHD (3840x2160) yang menghadirkan gambar tajam dan kontras tinggi. Menjalankan Android TV 11 dengan akses ke ribuan aplikasi streaming. Mendukung Google Assistant dan Chromecast built-in untuk kemudahan hiburan modern.', 'specifications' => ['Size' => '43 inch', 'Resolution' => '4K UHD', 'OS' => 'Android TV 11']],
            ['store_id' => 1, 'name' => 'Proyektor Mini Portabel',      'category' => 'Electronics', 'brand' => 'ProjectPro',   'price' => 1650000,  'stock' => 12,  'weight' => 600,  'description' => 'Proyektor mini portabel yang bisa menampilkan gambar hingga 120 inci. Resolusi full HD 1080p dengan kecerahan 300 ANSI lumen cukup untuk ruangan yang sedikit gelap. Baterai built-in tahan 3 jam untuk presentasi atau nonton film tanpa perlu colokan listrik.', 'specifications' => ['Brightness' => '300 ANSI', 'Resolution' => '1080p', 'Battery' => '3h']],
            ['store_id' => 1, 'name' => 'UPS 1200VA',                   'category' => 'Electronics', 'brand' => 'PowerSafe',    'price' => 880000,   'stock' => 9,   'weight' => 7000, 'description' => 'UPS (Uninterruptible Power Supply) 1200VA/720W untuk melindungi perangkat elektronik dari pemadaman listrik dan lonjakan tegangan. Dilengkapi 6 outlet dengan proteksi surge. Battery backup memberikan waktu cukup untuk menyimpan pekerjaan dan mematikan perangkat dengan aman.', 'specifications' => ['Capacity' => '1200VA/720W', 'Outlets' => '6', 'Battery' => 'Lead Acid']],
            ['store_id' => 1, 'name' => 'Printer Laser Monokrom',       'category' => 'Electronics', 'brand' => 'PrintPro',     'price' => 1950000,  'stock' => 7,   'weight' => 5500, 'description' => 'Printer laser monokrom untuk kebutuhan cetak dokumen volume tinggi. Kecepatan cetak 26 halaman per menit dengan resolusi 600dpi memastikan hasil cetak yang tajam. Konektivitas WiFi dan USB memudahkan pencetakan dari berbagai perangkat tanpa kabel.', 'specifications' => ['Speed' => '26ppm', 'Resolution' => '600dpi', 'Connectivity' => 'WiFi+USB']],

            // ==================== STORE 2 — Fashion Keren Store ====================
            ['store_id' => 2, 'name' => 'Kaos Polos Premium',          'category' => 'Fashion',  'brand' => 'BasicWear',    'price' => 150000,  'stock' => 100, 'weight' => 200, 'description' => 'Kaos polos berbahan cotton combed 30s yang lembut dan nyaman di kulit. Jahitan yang rapi dan kuat memastikan kaos tahan lama meski sering dicuci. Tersedia dalam berbagai warna pilihan yang timeless dan cocok dipadukan dengan berbagai outfit.', 'specifications' => ['Material' => 'Cotton Combed 30s', 'Size' => 'M', 'Color' => 'Navy']],
            ['store_id' => 2, 'name' => 'Kaos Oversize Streetwear',    'category' => 'Fashion',  'brand' => 'StreetStyle',  'price' => 210000,  'stock' => 80,  'weight' => 220, 'description' => 'Kaos oversize dengan potongan boxy yang sedang tren di kalangan anak muda. Bahan cotton combed 24s tebal dan tidak mudah melar. Desain minimalis yang mudah dipadukan dengan celana cargo, jeans, maupun rok untuk tampilan streetwear yang stylish.', 'specifications' => ['Material' => 'Cotton Combed 24s', 'Size' => 'L', 'Color' => 'Cream']],
            ['store_id' => 2, 'name' => 'Kemeja Flannel Kotak',        'category' => 'Fashion',  'brand' => 'CasualWear',   'price' => 280000,  'stock' => 60,  'weight' => 350, 'description' => 'Kemeja flannel dengan motif kotak klasik yang hangat dan nyaman. Bahan flannel lembut membuat kemeja ini cocok dipakai sebagai outer layer di hari yang sejuk. Bisa dikenakan diancingkan penuh atau sebagai outer layer di atas kaos polos.', 'specifications' => ['Material' => 'Flannel', 'Size' => 'L', 'Color' => 'Red-Black']],
            ['store_id' => 2, 'name' => 'Kemeja Oxford Slim Fit',      'category' => 'Fashion',  'brand' => 'FormalPlus',   'price' => 320000,  'stock' => 45,  'weight' => 300, 'description' => 'Kemeja Oxford slim fit dengan potongan yang rapi dan modern. Bahan Oxford cotton yang breathable membuat kemeja ini nyaman dipakai seharian di kantor. Cocok untuk tampilan formal maupun smart casual, bisa dipadukan dengan celana chino atau setelan jas.', 'specifications' => ['Material' => 'Oxford Cotton', 'Size' => 'M', 'Color' => 'White']],
            ['store_id' => 2, 'name' => 'Celana Chino Slim Fit',       'category' => 'Fashion',  'brand' => 'SlimFit',      'price' => 275000,  'stock' => 50,  'weight' => 400, 'description' => 'Celana chino slim fit dengan potongan modern yang mempertegas siluet tubuh. Bahan cotton blend yang nyaman dan sedikit stretch memudahkan bergerak. Cocok untuk tampilan casual maupun semi-formal, mudah dipadukan dengan kemeja, polo, maupun kaos polos.', 'specifications' => ['Material' => 'Cotton Blend', 'Size' => '32', 'Color' => 'Khaki']],
            ['store_id' => 2, 'name' => 'Celana Jogger Premium',       'category' => 'Fashion',  'brand' => 'SportWear',    'price' => 195000,  'stock' => 70,  'weight' => 350, 'description' => 'Celana jogger premium dari bahan fleece yang hangat dan lembut. Desain dengan elastik pinggang dan tali serut memastikan kenyamanan maksimal. Cocok untuk olahraga santai, jalan-jalan, maupun bersantai di rumah. Kantong samping dan belakang dengan resleting untuk keamanan barang bawaan.', 'specifications' => ['Material' => 'Fleece', 'Size' => 'L', 'Color' => 'Charcoal']],
            ['store_id' => 2, 'name' => 'Celana Jeans Slim Stretch',   'category' => 'Fashion',  'brand' => 'DenimCo',      'price' => 350000,  'stock' => 40,  'weight' => 500, 'description' => 'Celana jeans slim fit dari denim stretch yang nyaman dan tidak kaku. Potongan slim yang modern tetap memberikan kebebasan bergerak berkat kandungan elastan 2%. Warna medium blue yang timeless mudah dipadukan dengan berbagai jenis atasan.', 'specifications' => ['Material' => 'Denim Stretch', 'Size' => '31', 'Color' => 'Medium Blue']],
            ['store_id' => 2, 'name' => 'Jaket Hoodie Fleece',         'category' => 'Fashion',  'brand' => 'CozyWear',     'price' => 420000,  'original_price' => 520000,   'stock' => 35,  'weight' => 600, 'description' => 'Jaket hoodie dari bahan fleece 250gsm yang tebal dan hangat, sempurna untuk cuaca dingin. Bagian dalam berbulu halus memberikan kehangatan ekstra. Dilengkapi kantong depan kangguru dan tali hoodie yang bisa diatur. Desain simpel yang cocok untuk tampilan kasual sehari-hari.', 'specifications' => ['Material' => 'Fleece 250gsm', 'Size' => 'XL', 'Color' => 'Black']],
            ['store_id' => 2, 'name' => 'Jaket Bomber Varsity',        'category' => 'Fashion',  'brand' => 'StreetStyle',  'price' => 580000,  'stock' => 25,  'weight' => 700, 'description' => 'Jaket bomber varsity dengan desain sporty yang stylish. Kombinasi bahan polyester di bagian luar dengan lining satin di dalam memberikan tampilan premium. Detail bordir di dada dan lengan menambah karakter. Ribbing di kerah, manset, dan hem memberikan fit yang pas.', 'specifications' => ['Material' => 'Polyester', 'Size' => 'L', 'Color' => 'Olive Green']],
            ['store_id' => 2, 'name' => 'Jaket Windbreaker',           'category' => 'Fashion',  'brand' => 'OutdoorPro',   'price' => 480000,  'stock' => 30,  'weight' => 450, 'description' => 'Jaket windbreaker dari bahan nylon ripstop yang ringan namun kuat. Lapisan DWR (Durable Water Repellent) membuatnya tahan cipratan hujan. Bisa dilipat sangat kecil dan dimasukkan ke dalam saku sendiri, cocok untuk traveling atau aktivitas outdoor.', 'specifications' => ['Material' => 'Nylon Ripstop', 'Size' => 'L', 'Water Resistant' => 'Yes']],
            ['store_id' => 2, 'name' => 'Dress Casual Floral',         'category' => 'Fashion',  'brand' => 'LovelyWear',   'price' => 220000,  'stock' => 55,  'weight' => 250, 'description' => 'Dress casual dengan motif floral yang feminin dan ceria. Bahan viscose yang jatuh dan adem nyaman dipakai sepanjang hari. Potongan A-line yang universal cocok untuk berbagai bentuk tubuh. Cocok untuk hangout, piknik, atau acara casual.', 'specifications' => ['Material' => 'Viscose', 'Size' => 'M', 'Color' => 'Floral Pink']],
            ['store_id' => 2, 'name' => 'Dress Midi Formal',           'category' => 'Fashion',  'brand' => 'ElegantStyle', 'price' => 385000,  'stock' => 30,  'weight' => 300, 'description' => 'Dress midi elegan dari bahan crepe berkualitas yang jatuh dengan indah. Siluet yang flattering cocok untuk acara formal, pernikahan, maupun dinner. Detail belahan kecil di bagian belakang memberikan keanggunan saat berjalan.', 'specifications' => ['Material' => 'Crepe', 'Size' => 'M', 'Color' => 'Navy Blue']],
            ['store_id' => 2, 'name' => 'Rok A-Line Polos',            'category' => 'Fashion',  'brand' => 'LovelyWear',   'price' => 165000,  'stock' => 45,  'weight' => 200, 'description' => 'Rok A-line dengan siluet yang mengembang ke bawah, cocok untuk semua bentuk tubuh. Bahan cotton yang nyaman dan adem untuk iklim tropis. Pinggang elastik yang nyaman tanpa kancing atau resleting. Mudah dipadukan dengan berbagai jenis atasan.', 'specifications' => ['Material' => 'Cotton', 'Size' => 'M', 'Color' => 'Dusty Pink']],
            ['store_id' => 2, 'name' => 'Blouse Wanita Ruffle',        'category' => 'Fashion',  'brand' => 'LovelyWear',   'price' => 185000,  'stock' => 50,  'weight' => 200, 'description' => 'Blouse wanita dengan detail ruffle di bagian depan yang feminin dan elegan. Bahan chiffon yang lembut dan ringan memberikan kesan anggun. Cocok untuk tampilan semi-formal di kantor maupun acara santai. Tersedia dalam pilihan warna yang versatile.', 'specifications' => ['Material' => 'Chiffon', 'Size' => 'M', 'Color' => 'White']],
            ['store_id' => 2, 'name' => 'Sepatu Sneakers Casual',      'category' => 'Fashion',  'brand' => 'StepPro',      'price' => 450000,  'stock' => 40,  'weight' => 800, 'description' => 'Sneakers canvas klasik dengan desain all-white yang bersih dan versatile. Sol karet yang lentur dan nyaman untuk penggunaan sehari-hari. Cocok dipadukan dengan celana jeans, chino, maupun dress casual. Mudah dibersihkan dan tahan lama.', 'specifications' => ['Material' => 'Canvas', 'Size' => '42', 'Color' => 'All White']],
            ['store_id' => 2, 'name' => 'Sepatu Formal Pantofel',      'category' => 'Fashion',  'brand' => 'FormalFoot',   'price' => 620000,  'stock' => 20,  'weight' => 900, 'description' => 'Sepatu formal pantofel dari bahan genuine leather yang berkualitas tinggi. Jahitan yang presisi dan sol karet anti-slip memberikan kenyamanan dan keamanan. Cocok untuk acara formal, presentasi, atau sehari-hari di kantor. Tampilannya yang klasik tidak lekang oleh waktu.', 'specifications' => ['Material' => 'Genuine Leather', 'Size' => '42', 'Color' => 'Black']],
            ['store_id' => 2, 'name' => 'Sandal Gunung Outdoor',       'category' => 'Fashion',  'brand' => 'OutdoorPro',   'price' => 280000,  'stock' => 35,  'weight' => 500, 'description' => 'Sandal gunung yang kokoh dan nyaman untuk aktivitas outdoor. Kombinasi upper nylon yang kuat dengan sol karet Vibram memberikan cengkeraman yang baik di berbagai medan. Tali yang bisa disesuaikan memastikan fit yang sempurna dan aman saat mendaki.', 'specifications' => ['Material' => 'Rubber+Nylon', 'Size' => '42', 'Color' => 'Dark Brown']],
            ['store_id' => 2, 'name' => 'Tas Ransel Laptop 15"',       'category' => 'Fashion',  'brand' => 'BagPro',       'price' => 380000,  'stock' => 28,  'weight' => 700, 'description' => 'Tas ransel fungsional dengan kompartemen khusus laptop 15 inci yang berpadding. Kapasitas 30L dengan banyak kantong terorganisir untuk menyimpan aksesoris, dokumen, dan perlengkapan harian. Tali bahu ergonomis yang empuk mengurangi beban di pundak saat digunakan lama.', 'specifications' => ['Material' => 'Polyester 600D', 'Capacity' => '30L', 'Color' => 'Black']],
            ['store_id' => 2, 'name' => 'Tas Selempang Mini',          'category' => 'Fashion',  'brand' => 'BagPro',       'price' => 175000,  'stock' => 40,  'weight' => 300, 'description' => 'Tas selempang mini dari bahan PU leather berkualitas yang tampak mewah. Ukurannya yang compact namun cukup untuk menyimpan dompet, ponsel, dan kunci. Tali yang bisa disesuaikan panjangnya membuatnya nyaman dipakai berbagai postur. Cocok untuk hangout atau jalan-jalan santai.', 'specifications' => ['Material' => 'PU Leather', 'Capacity' => '2L', 'Color' => 'Tan Brown']],
            ['store_id' => 2, 'name' => 'Topi Baseball Polos',         'category' => 'Fashion',  'brand' => 'CapStyle',     'price' => 95000,   'stock' => 80,  'weight' => 100, 'description' => 'Topi baseball polos dari bahan cotton twill yang nyaman dan breathable. Desain six-panel klasik dengan bordir logo minimal. Bagian belakang dengan strap yang bisa disesuaikan cocok untuk semua ukuran kepala. Sempurna untuk melindungi dari sinar matahari sekaligus melengkapi outfit kasual.', 'specifications' => ['Material' => 'Cotton Twill', 'Size' => 'Free Size', 'Color' => 'Black']],
            ['store_id' => 2, 'name' => 'Ikat Pinggang Kulit',         'category' => 'Fashion',  'brand' => 'BeltPro',      'price' => 120000,  'stock' => 60,  'weight' => 150, 'description' => 'Ikat pinggang dari bahan PU leather yang tampak seperti kulit asli dengan harga terjangkau. Gesper logam anti-karat dengan desain minimalis yang elegan. Lebar 3cm yang proporsional cocok untuk celana casual maupun formal. Panjang 120cm yang bisa dipotong sesuai ukuran.', 'specifications' => ['Material' => 'PU Leather', 'Size' => '120cm', 'Color' => 'Black']],
            ['store_id' => 2, 'name' => 'Kaos Kaki Premium Pack 3',    'category' => 'Fashion',  'brand' => 'SocksPro',     'price' => 65000,   'stock' => 150, 'weight' => 80,  'description' => 'Paket 3 pasang kaos kaki premium dari bahan cotton combed yang lembut dan menyerap keringat dengan baik. Rajutan rapat dan elastis yang tidak mudah melar. Tersedia dalam kombinasi warna yang variatif. Cocok untuk penggunaan sehari-hari baik formal maupun casual.', 'specifications' => ['Material' => 'Cotton', 'Size' => '39-43', 'Color' => 'Mixed']],
            ['store_id' => 2, 'name' => 'Pakaian Dalam Pria Pack 3',   'category' => 'Fashion',  'brand' => 'BasicWear',    'price' => 110000,  'stock' => 100, 'weight' => 120, 'description' => 'Paket 3 pcs pakaian dalam pria dari bahan cotton combed yang lembut dan nyaman sepanjang hari. Elastis pinggang yang kuat dan tidak mudah kendur. Jahitan flatlock yang halus mencegah iritasi kulit. Tersedia dalam pilihan warna yang bervariasi.', 'specifications' => ['Material' => 'Cotton Combed', 'Size' => 'M', 'Color' => 'Mixed']],
            ['store_id' => 2, 'name' => 'Dompet Pria Slim',            'category' => 'Fashion',  'brand' => 'WalletPro',    'price' => 145000,  'stock' => 45,  'weight' => 80,  'description' => 'Dompet pria slim yang tipis dan tidak membuat saku terasa penuh. Tersedia 8 slot kartu yang cukup untuk menyimpan berbagai kartu kredit, debit, dan identitas. Bahan PU leather premium yang tahan lama dengan jahitan yang rapi. Desain simpel yang cocok untuk penggunaan formal maupun kasual.', 'specifications' => ['Material' => 'PU Leather', 'Card Slots' => '8', 'Color' => 'Dark Brown']],
            ['store_id' => 2, 'name' => 'Kacamata Hitam UV400',        'category' => 'Fashion',  'brand' => 'SunStyle',     'price' => 185000,  'stock' => 55,  'weight' => 50,  'description' => 'Kacamata hitam stylish dengan lensa polarized yang melindungi mata dari silau dan sinar UV berbahaya hingga UV400. Frame metal yang ringan dan kokoh dengan engsel spring untuk kenyamanan pemakaian. Cocok untuk berkendara, aktivitas outdoor, maupun tampilan kasual sehari-hari.', 'specifications' => ['Frame' => 'Metal', 'Lens' => 'Polarized', 'UV Protection' => 'UV400']],

            // ==================== STORE 3 — Toko Serba Ada ====================
            ['store_id' => 3, 'name' => 'Serum Vitamin C 30ml',           'category' => 'Beauty',   'brand' => 'GlowSkin',   'price' => 185000,  'original_price' => 220000,   'stock' => 60,  'weight' => 80,  'description' => 'Serum vitamin C dengan konsentrasi 15% yang efektif mencerahkan kulit kusam dan meratakan warna kulit. Formula stabil dengan tambahan vitamin E dan ferulic acid untuk hasil yang lebih optimal. Penggunaan rutin selama 4 minggu terlihat kulit lebih cerah, bercahaya, dan noda hitam memudar.', 'specifications' => ['Volume' => '30ml', 'Type' => 'Brightening', 'Skin Type' => 'All Skin']],
            ['store_id' => 3, 'name' => 'Moisturizer SPF 30',             'category' => 'Beauty',   'brand' => 'GlowSkin',   'price' => 155000,  'stock' => 70,  'weight' => 100, 'description' => 'Pelembap wajah ringan dengan perlindungan SPF 30 yang cocok digunakan sebagai langkah terakhir skincare pagi hari. Formula non-comedogenic tidak menyumbat pori-pori. Tekstur gel-cream yang ringan cepat meresap dan tidak meninggalkan rasa berminyak.', 'specifications' => ['Volume' => '50ml', 'SPF' => '30', 'Skin Type' => 'Normal-Dry']],
            ['store_id' => 3, 'name' => 'Sunscreen SPF 50 PA++++',        'category' => 'Beauty',   'brand' => 'SunGuard',   'price' => 125000,  'stock' => 90,  'weight' => 80,  'description' => 'Sunscreen ringan dengan perlindungan tinggi SPF 50 PA++++ yang efektif melindungi kulit dari sinar UVA dan UVB. Finish matte yang tahan lama cocok untuk kulit berminyak. Tidak meninggalkan white cast sehingga aman untuk semua warna kulit. Water resistant hingga 80 menit.', 'specifications' => ['Volume' => '30ml', 'SPF' => '50', 'Finish' => 'Matte']],
            ['store_id' => 3, 'name' => 'Face Wash Gentle Foam',          'category' => 'Beauty',   'brand' => 'CleanFace',  'price' => 75000,   'stock' => 100, 'weight' => 120, 'description' => 'Sabun cuci muka berbusa lembut yang membersihkan kotoran dan sebum tanpa membuat kulit terasa kering atau tertarik. Formula pH-balanced cocok untuk semua jenis kulit termasuk kulit sensitif. Kandungan aloe vera membantu menjaga kelembapan kulit setelah mencuci muka.', 'specifications' => ['Volume' => '100ml', 'Type' => 'Foam', 'Skin Type' => 'All Skin']],
            ['store_id' => 3, 'name' => 'Toner Hydrating HA',             'category' => 'Beauty',   'brand' => 'GlowSkin',   'price' => 140000,  'stock' => 65,  'weight' => 150, 'description' => 'Toner hidrasi dengan kandungan Hyaluronic Acid (HA) konsentrasi tinggi yang mampu menyimpan kelembapan 1000x beratnya. Tekstur cair yang ringan mudah meresap cepat ke kulit. Gunakan setelah pembersih untuk mempersiapkan kulit menyerap serum dan pelembap lebih baik.', 'specifications' => ['Volume' => '150ml', 'Key Ingredient' => 'Hyaluronic Acid', 'Skin Type' => 'Dry-Normal']],
            ['store_id' => 3, 'name' => 'Sheet Mask Pack 5pcs',           'category' => 'Beauty',   'brand' => 'MaskPro',    'price' => 55000,   'stock' => 120, 'weight' => 100, 'description' => 'Paket 5 lembar sheet mask dengan esens yang kaya akan kandungan hidrasi. Kain mask yang lembut dan tipis menempel sempurna di wajah untuk penyerapan bahan aktif yang optimal. Gunakan 2-3 kali seminggu untuk kulit yang lembap, kenyal, dan bercahaya. Cocok sebagai skincare malam hari.', 'specifications' => ['Qty' => '5 sheets', 'Type' => 'Hydrating', 'Skin Type' => 'All Skin']],
            ['store_id' => 3, 'name' => 'Lip Balm SPF 15',               'category' => 'Beauty',   'brand' => 'LipCare',    'price' => 35000,   'stock' => 150, 'weight' => 20,  'description' => 'Lip balm dengan formula pelembap intensif yang melindungi dan merawat bibir kering dan pecah-pecah. Kandungan SPF 15 melindungi bibir dari kerusakan akibat paparan sinar matahari. Formula bebas pewarna dan pewangi buatan, aman untuk bibir sensitif.', 'specifications' => ['Volume' => '4g', 'SPF' => '15', 'Flavor' => 'Original']],
            ['store_id' => 3, 'name' => 'Foundation Liquid Matte',        'category' => 'Beauty',   'brand' => 'MakeupPro',  'price' => 220000,  'stock' => 40,  'weight' => 80,  'description' => 'Foundation cair dengan formula full coverage yang menutup noda, bekas jerawat, dan ketidaksempurnaan kulit lainnya. Finish matte yang tahan lama hingga 12 jam tanpa perlu touch-up. Formula ringan yang tidak terasa berat di kulit meski memberikan coverage penuh.', 'specifications' => ['Volume' => '30ml', 'Finish' => 'Matte', 'Coverage' => 'Full']],
            ['store_id' => 3, 'name' => 'Shampoo Anti Rambut Rontok',     'category' => 'Beauty',   'brand' => 'HairCare',   'price' => 95000,   'stock' => 80,  'weight' => 400, 'description' => 'Sampo dengan formula khusus anti rambut rontok yang memperkuat akar rambut dari dalam. Kandungan biotin, keratin, dan ginseng extract merangsang pertumbuhan rambut baru. Bebas sulfat dan paraben, aman untuk penggunaan sehari-hari pada semua jenis rambut.', 'specifications' => ['Volume' => '340ml', 'Type' => 'Anti Hair Fall', 'Hair Type' => 'All']],
            ['store_id' => 3, 'name' => 'Body Lotion Whitening',          'category' => 'Beauty',   'brand' => 'BodyGlow',   'price' => 65000,   'stock' => 100, 'weight' => 250, 'description' => 'Lotion tubuh dengan formula pencerah yang mengandung niacinamide dan vitamin C untuk mencerahkan kulit secara merata. SPF 15 memberikan perlindungan dasar dari sinar matahari. Tekstur ringan yang cepat meresap dan tidak lengket, cocok untuk penggunaan sehari-hari.', 'specifications' => ['Volume' => '200ml', 'Type' => 'Whitening', 'SPF' => 'SPF 15']],
            ['store_id' => 3, 'name' => 'Tumbler Stainless 500ml',        'category' => 'Home',     'brand' => 'DrinkPro',   'price' => 145000,  'stock' => 50,  'weight' => 350, 'description' => 'Tumbler stainless steel double-wall vacuum insulated yang menjaga minuman dingin hingga 24 jam dan panas hingga 12 jam. Kapasitas 500ml ideal untuk kebutuhan minum harian. Tutup anti-tumpah yang aman dibawa di dalam tas. Bebas BPA dan food grade.', 'specifications' => ['Capacity' => '500ml', 'Material' => 'Stainless 304', 'Keep Cold' => '24h']],
            ['store_id' => 3, 'name' => 'Botol Minum Kaca 600ml',         'category' => 'Home',     'brand' => 'EcoLife',    'price' => 85000,   'stock' => 60,  'weight' => 400, 'description' => 'Botol minum kaca borosilikat yang tahan terhadap perubahan suhu ekstrem. Bebas BPA dan tidak meninggalkan rasa atau bau pada minuman. Sleeve silikon anti-slip melindungi botol dari benturan. Pilihan ramah lingkungan sebagai pengganti botol plastik sekali pakai.', 'specifications' => ['Capacity' => '600ml', 'Material' => 'Borosilicate Glass', 'BPA Free' => 'Yes']],
            ['store_id' => 3, 'name' => 'Organizer Meja Kayu',            'category' => 'Home',     'brand' => 'WoodCraft',  'price' => 225000,  'stock' => 25,  'weight' => 1200,'description' => 'Organizer meja dari kayu solid dengan finishing natural yang elegan. Tersedia 6 kompartemen berbeda ukuran untuk menyimpan alat tulis, ponsel, kartu nama, dan berbagai perlengkapan meja kerja. Desain minimalis yang cocok untuk ruang kerja modern maupun bergaya Skandinavia.', 'specifications' => ['Material' => 'Solid Wood', 'Compartments' => '6', 'Color' => 'Natural Brown']],
            ['store_id' => 3, 'name' => 'Cermin Dinding Oval 50cm',       'category' => 'Home',     'brand' => 'HomeDecor',  'price' => 185000,  'stock' => 20,  'weight' => 1500,'description' => 'Cermin dinding oval dengan frame metal emas yang elegan dan modern. Ukuran 50x70cm cukup untuk cermin rias sekaligus dekorasi dinding yang memperindah ruangan. Mudah dipasang dengan gantungan yang sudah disertakan. Cocok untuk kamar tidur, ruang tamu, atau lorong rumah.', 'specifications' => ['Size' => '50x70cm', 'Frame' => 'Metal Gold', 'Type' => 'Wall Mirror']],
            ['store_id' => 3, 'name' => 'Pot Tanaman Keramik',            'category' => 'Home',     'brand' => 'GreenHome',  'price' => 75000,   'stock' => 40,  'weight' => 800, 'description' => 'Pot tanaman dari keramik berkualitas dengan warna terracotta alami yang cantik dan hangat. Lubang drainase di bagian bawah mencegah akar tanaman membusuk karena genangan air. Cocok untuk tanaman hias indoor seperti kaktus, sukulen, dan tanaman pot kecil lainnya.', 'specifications' => ['Size' => '15cm', 'Material' => 'Ceramic', 'Color' => 'Terracotta']],
            ['store_id' => 3, 'name' => 'Lilin Aromaterapi Soy Wax',      'category' => 'Home',     'brand' => 'AromaHome',  'price' => 95000,   'stock' => 55,  'weight' => 200, 'description' => 'Lilin aromaterapi dari 100% soy wax alami yang ramah lingkungan dan terbakar lebih bersih tanpa jelaga. Wangi lavender yang menenangkan membantu relaksasi dan meningkatkan kualitas tidur. Waktu bakar hingga 45 jam. Cocok sebagai dekorasi sekaligus aromaterapi ruangan.', 'specifications' => ['Weight' => '200g', 'Wax' => 'Soy', 'Burn Time' => '45h', 'Scent' => 'Lavender']],
            ['store_id' => 3, 'name' => 'Diffuser Aroma Ultrasonic',      'category' => 'Home',     'brand' => 'AromaHome',  'price' => 280000,  'stock' => 20,  'weight' => 400, 'description' => 'Diffuser ultrasonic yang menggunakan gelombang suara frekuensi tinggi untuk mengubah air dan essential oil menjadi uap halus yang menyebarkan aroma ke seluruh ruangan. Kapasitas 300ml cukup untuk dioperasikan hingga 8 jam. Dilengkapi lampu LED warna-warni yang bisa diatur sebagai night light.', 'specifications' => ['Capacity' => '300ml', 'Timer' => 'Yes', 'Color' => 'White']],
            ['store_id' => 3, 'name' => 'Set Alat Makan Stainless 4pcs',  'category' => 'Home',     'brand' => 'KitchenPro', 'price' => 125000,  'stock' => 35,  'weight' => 300, 'description' => 'Set alat makan lengkap terdiri dari sendok makan, garpu, sendok teh, dan pisau makan. Terbuat dari stainless steel 18/10 food grade yang tidak berkarat dan tahan lama. Desain ergonomis yang nyaman digenggam. Aman untuk mesin cuci piring.', 'specifications' => ['Material' => 'Stainless 18/10', 'Pieces' => '4', 'Dishwasher Safe' => 'Yes']],
            ['store_id' => 3, 'name' => 'Rak Buku Dinding Kayu',          'category' => 'Home',     'brand' => 'WoodCraft',  'price' => 195000,  'stock' => 18,  'weight' => 1800,'description' => 'Rak buku dinding minimalis dari bahan MDF dengan finishing walnut yang elegan. Ukuran 60x20cm cukup untuk menyimpan buku, tanaman kecil, atau dekorasi. Mampu menahan beban hingga 10kg. Pemasangan mudah dengan mounting hardware yang sudah disertakan.', 'specifications' => ['Size' => '60x20cm', 'Material' => 'MDF', 'Load' => '10kg', 'Color' => 'Walnut']],
            ['store_id' => 3, 'name' => 'Bantal Sofa 45x45cm',            'category' => 'Home',     'brand' => 'HomeComfort','price' => 85000,   'stock' => 60,  'weight' => 500, 'description' => 'Bantal sofa dekoratif berukuran 45x45cm dengan isian microfiber yang empuk dan tidak kempes. Sarung bantal yang bisa dilepas memudahkan pencucian. Tersedia dalam berbagai pilihan warna dan motif untuk mempercantik ruang tamu atau kamar tidur.', 'specifications' => ['Size' => '45x45cm', 'Fill' => 'Microfiber', 'Cover' => 'Removable']],
            ['store_id' => 3, 'name' => 'Matras Yoga Premium 6mm',        'category' => 'Sports',   'brand' => 'FitLife',    'price' => 250000,  'stock' => 30,  'weight' => 900, 'description' => 'Matras yoga dari bahan TPE (Thermoplastic Elastomer) yang ramah lingkungan dan bebas bahan berbahaya. Ketebalan 6mm memberikan bantalan yang cukup untuk sendi namun tetap memberikan koneksi yang baik ke lantai. Permukaan double-sided non-slip mencegah tergelincir saat berlatih.', 'specifications' => ['Thickness' => '6mm', 'Material' => 'TPE', 'Size' => '183x61cm', 'Non-Slip' => 'Yes']],
            ['store_id' => 3, 'name' => 'Resistance Band Set 5pcs',       'category' => 'Sports',   'brand' => 'FitLife',    'price' => 95000,   'stock' => 50,  'weight' => 300, 'description' => 'Set 5 resistance band dengan tingkat resistensi berbeda (10-40 lbs) dari bahan natural latex yang kuat dan elastis. Cocok untuk latihan kekuatan, rehabilitasi otot, peregangan, dan pilates. Ringan dan portable, bisa digunakan di mana saja tanpa perlu peralatan gym.', 'specifications' => ['Resistance' => '10-40 lbs', 'Material' => 'Natural Latex', 'Qty' => '5']],
            ['store_id' => 3, 'name' => 'Dumbbell 5kg Hex',               'category' => 'Sports',   'brand' => 'IronFit',    'price' => 185000,  'stock' => 20,  'weight' => 5000,'description' => 'Dumbbell hexagonal 5kg dengan coating karet yang melindungi lantai dan meredam suara saat diletakkan. Bentuk hexagonal mencegah dumbbell menggelinding. Pegangan baja dengan tekstur knurling memastikan cengkeraman yang kuat dan tidak licin saat tangan berkeringat.', 'specifications' => ['Weight' => '5kg', 'Material' => 'Rubber Coated Iron', 'Shape' => 'Hexagonal']],
            ['store_id' => 3, 'name' => 'Tas Gym Duffle 40L',             'category' => 'Sports',   'brand' => 'FitPro',     'price' => 220000,  'stock' => 25,  'weight' => 600, 'description' => 'Tas duffle gym berkapasitas 40L yang luas dengan kompartemen terorganisir. Terdapat kantong khusus sepatu yang terpisah untuk menjaga kebersihan barang lainnya. Tali bahu yang bisa dilepas memungkinkan pemakaian sebagai tas tangan maupun selempang.', 'specifications' => ['Capacity' => '40L', 'Material' => 'Polyester', 'Shoe Compartment' => 'Yes']],
            ['store_id' => 3, 'name' => 'Sepatu Lari Running Pro',        'category' => 'Sports',   'brand' => 'RunFast',    'price' => 680000,  'original_price' => 850000,   'stock' => 22,  'weight' => 700, 'description' => 'Sepatu lari berteknologi tinggi dengan sol EVA foam yang ringan dan responsif, memberikan cushioning optimal untuk setiap langkah. Upper mesh breathable menjaga kaki tetap segar saat berlari. Desain yang aerodinamis dan teknologi anti-twist menjaga stabilitas kaki saat berlari jarak jauh.', 'specifications' => ['Size' => '42', 'Sole' => 'EVA Foam', 'Upper' => 'Mesh Breathable']],
            ['store_id' => 3, 'name' => 'Kopi Arabika Single Origin 250g','category' => 'Food',     'brand' => 'CoffeePro',  'price' => 95000,   'stock' => 70,  'weight' => 280, 'description' => 'Biji kopi arabika single origin dari dataran tinggi Flores dengan profil rasa cokelat, karamel, dan sedikit fruity yang kompleks. Dipetik secara selektif dan diproses dengan metode natural untuk menghasilkan rasa yang kaya. Roasting medium menjaga keseimbangan keasaman dan body.', 'specifications' => ['Weight' => '250g', 'Origin' => 'Flores', 'Roast' => 'Medium', 'Form' => 'Whole Bean']],
            ['store_id' => 3, 'name' => 'Teh Herbal Chamomile 20 Sachet', 'category' => 'Food',     'brand' => 'TeaLife',    'price' => 45000,   'stock' => 90,  'weight' => 60,  'description' => 'Teh herbal chamomile bebas kafein yang menenangkan pikiran dan membantu relaksasi. Terbuat dari bunga chamomile pilihan tanpa tambahan bahan pengawet atau pewarna. Minum secangkir sebelum tidur untuk membantu mendapatkan tidur yang lebih nyenyak dan berkualitas.', 'specifications' => ['Qty' => '20 sachet', 'Type' => 'Caffeine Free', 'Flavor' => 'Chamomile']],
            ['store_id' => 3, 'name' => 'Madu Hutan Murni 500g',          'category' => 'Food',     'brand' => 'NaturalGood','price' => 135000,  'stock' => 40,  'weight' => 550, 'description' => 'Madu hutan murni dari lebah liar di hutan Kalimantan tanpa campuran apapun. Kaya akan enzim, antioksidan, dan mineral alami yang bermanfaat untuk kesehatan. Warna gelap dengan aroma khas yang kuat menandakan kualitas dan kemurniannya. Tidak dipanaskan untuk menjaga kandungan nutrisi tetap utuh.', 'specifications' => ['Weight' => '500g', 'Type' => 'Raw Honey', 'Origin' => 'Kalimantan']],
            ['store_id' => 3, 'name' => 'Granola Homemade 300g',          'category' => 'Food',     'brand' => 'HealthyBite','price' => 65000,   'stock' => 55,  'weight' => 320, 'description' => 'Granola buatan sendiri dari campuran oat, kacang-kacangan, biji-bijian, dan madu alami yang dipanggang hingga renyah. Bebas gluten, tanpa pengawet, dan tanpa pemanis buatan. Kaya serat dan protein untuk sarapan sehat atau camilan bergizi. Cocok dimakan bersama yogurt atau susu.', 'specifications' => ['Weight' => '300g', 'Type' => 'Gluten Free', 'Flavor' => 'Honey Almond']],
            ['store_id' => 3, 'name' => 'Protein Bar Box 12pcs',          'category' => 'Food',     'brand' => 'FitFood',    'price' => 185000,  'stock' => 35,  'weight' => 480, 'description' => 'Paket 12 batang protein bar dengan kandungan 20g protein per batang untuk mendukung pertumbuhan dan pemulihan otot. Rasa cokelat yang lezat membuatnya terasa seperti cemilan bukan suplemen. Rendah gula dengan pemanis alami stevia. Cocok dikonsumsi sebelum atau sesudah latihan.', 'specifications' => ['Qty' => '12 bars', 'Protein' => '20g/bar', 'Flavor' => 'Chocolate']],
            ['store_id' => 3, 'name' => 'Olive Oil Extra Virgin 500ml',   'category' => 'Food',     'brand' => 'NaturalGood','price' => 125000,  'stock' => 45,  'weight' => 600, 'description' => 'Minyak zaitun extra virgin dari perkebunan zaitun terpilih di Spanyol dengan teknik cold-press pertama untuk kualitas tertinggi. Rasa fruity dengan sedikit pedasnya yang khas menandakan kemurniannya. Kaya akan antioksidan dan lemak tak jenuh tunggal yang baik untuk kesehatan jantung.', 'specifications' => ['Volume' => '500ml', 'Type' => 'Extra Virgin', 'Origin' => 'Spain']],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
